apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gigashop

resources:
  - namespace.yaml
  - databases/catalogdb-deployment.yaml
  - databases/basketdb-deployment.yaml
  - databases/orderdb-deployment.yaml
  - infrastructure/redis-deployment.yaml
  - infrastructure/rabbitmq-deployment.yaml
  - services/catalog-api-deployment.yaml
  - services/basket-api-deployment.yaml
  - services/order-api-deployment.yaml
  - services/discount-grpc-deployment.yaml
  - gateway/apigateway-deployment.yaml
  - frontend/web-deployment.yaml
  - ingress/ingress.yaml
