services:
  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres 
    
  distributedcache:
    image: redis 
    
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
  
  order.api:
    image: order.api
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile
  
  discount.grpc:
    image: discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2025-latest
  
  messagebroker:
    image: rabbitmq:management
    
  yarpapigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
  
  web:
    image: web
    build:
      context: .
      dockerfile: Web/Dockerfile
      args:
        VITE_CART_SERVICE_URL: http://localhost:6004/basket-service
        VITE_PRODUCT_SERVICE_URL: http://localhost:6004/catalog-service
        VITE_USER_SERVICE_URL: http://localhost:6004/order-service
    
volumes:
  postgres_catalog:
  postgres_basket:
  mssql_order:
    driver: local
